import math

#RESOLUTION = WIDTH, HEIGHT = 320, 200
#RESOLUTION = WIDTH, HEIGHT = 480, 300
#RESOLUTION = WIDTH, HEIGHT = 640, 400
#RESOLUTION = WIDTH, HEIGHT = 1280, 800
#RESOLUTION = WIDTH, HEIGHT = 1600, 1000
RESOLUTION = WIDTH, HEIGHT = 1920, 1200
GAME_SCALE = WIDTH // 320
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

IS_2D_MODEL_ENABLED = False

GAME_BG_COLOR = '#212121'
#GAME_BG_COLOR = 'black'
CEILING_COLOR = (0, 108, 112)
FLOOR_COLOR = (70, 70, 70)
MAP_BLOCK_COLOR = 'white'
MAP_RECT_SIZE = 14

PLAYER_START_POSITION = 29.5, 57.5
PLAYER_ANGLE = 0 #-3.14 / 2
PLAYER_SPEED = 0.004
PLAYER_ROTATION_SPEED = 0.002
PLAYER_SIZE = 3 
PLAYER_SIZE_SCALE = 70
PLAYER_COLOR = 'green'
PLAYER_ANGLE_COLOR = 'yellow'
PLAYER_MAX_HEALTH = 100
PLAYER_MAX_AMMO = 99
PLAYER_MAX_LIVES = 9

MOUSE_SENSITIVITY = 0.00015
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = HALF_WIDTH
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT
MOUSE_BORDER_TOP = HALF_HEIGHT
MOUSE_BORDER_BOTTOM = HEIGHT - MOUSE_BORDER_TOP

#RAY CASTING
FIELD_OF_VIEW = math.pi / 3 #60°
HALF_FIELD_OF_VIEW = FIELD_OF_VIEW / 2
NUMBER_OF_RAYS = WIDTH // 2
HALF_NUMBER_OF_RAYS = NUMBER_OF_RAYS // 2
DELTA_ANGLE = FIELD_OF_VIEW / NUMBER_OF_RAYS
MAX_DEPTH = 30 

SCREEN_DISTANCE_TO_PLAYER = HALF_WIDTH / math.tan(HALF_FIELD_OF_VIEW)
RAY_SCALE = WIDTH // NUMBER_OF_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

TMX_NPC_LAYER_INDEX = 1
TMX_ITEMS_LAYER_INDEX = 2
